Waittask refactor (#2190)
* Waittask refactor

* remove typescript code

* Fix some javascript calls

* Some improvements

* cr

* Fix some tests

* passing tests

* WaitTask Refactor - Fix Evaluation failed: TypeError: fun is not a function (#2192)

* Fix Evaluation failed: TypeError: fun is not a function

- The whitespace is causing the new Function() call to fail.

* Alternate fix

* Fix ShouldRespectTimeout test

* Fix failing test

---------

Co-authored-by: Alex Maitland <amaitland@users.noreply.github.com>