WaitTask Refactor - Fix Evaluation failed: TypeError: fun is not a function (#2192)
* Fix Evaluation failed: TypeError: fun is not a function

- The whitespace is causing the new Function() call to fail.

* Alternate fix

* Fix ShouldRespectTimeout test